- .gitignore
- src/app/blog/[id]/page.tsx
- src/app/blog/page.tsx
- src/app/events/[id]/page.tsx
- src/app/events/page.tsx
- src/app/layout.tsx
- src/app/members/page.tsx
- src/app/page.tsx
- src/app/projects/[id]/page.tsx
- src/app/projects/page.tsx
Next.JS 기초 Route를 구현하였습니다.
- 각 페이지에 대한 Route 디렉토리를 지정하였습니다.
- Blog 및 Event의 경우는, `id` 값으로 Dynamic Route를 하도록 지정하였습니다.
- `.gitignore`에 Jetbrains 계열 IDE 관련 사항을 추가하였습니다.
> [DEV] 기초 Route 구현

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- Rules.md
Project 컨벤션에 대한 문서를 구성하였습니다.
- `Rules.md` 문서를 생성하고, Commit / Branch / Issue / PR 각각에 대한 상세한 컨벤션 사항을 작성하였습니다.
- `.github` 디렉토리에 Issue와 PR 항목의 템플릿 문서를 구성하였습니다.
> [DOC] Proejct 컨벤션 문서 구성

- README.md
- Rules.md
- package.json
- src/app/layout.tsx
- src/app/page.tsx
- src/components/icons/Gdsc.tsx
- src/components/icons/index.ts
- src/components/index.ts
- src/components/link/Link.tsx
공통 navbar를 제작했습니다.
- navbar 각 버튼은 hover시에 underline이 확장되는 애니메이션을 가지고 있습니다.
- Home버튼을 Logo로 대체했습니다.
- next `<Link />` 컴포넌트에 `LinkPath` 타입을 적용해 타입 안전성을 추가했습니다.
```tsx
import { Link$ } from "~/components"
const Some = () => {
// memberss는 유효한 href 경로가 아니므로 typescript가 에러매세지를 던집니다!
return <Link$ href="/memberss">
}
```
close #6
> [DEV] 페이지 공통 nav bar 구현

- src/app/layout.tsx
- src/app/page.tsx
- tailwind.config.js
기본 스타일 property를 업데이트 합니다.
- eng 메인 폰트를 poppins로 변경합니다.
- `background` property를 `theme-background`로 변경합니다.
- `theme-font` property를 추가했습니다.
> [DEV] Tailwind CSS 공통 스타일 추가 설정

- next.config.js
- src/app/events/_components/eventCard.tsx
- src/app/events/page.tsx
event card 만들었습니다
- 이미지를 어떻게 불러올지 몰라 주황색으로 보이기만 하게 만들었습니다.
> [DEV] 이벤트페이지 카드

- src/app/events/_components/eventCard.tsx
- src/app/events/page.tsx
여진씨가 만든 이벤트 카드 배치하는 작업을 했습니다.
- 창 사이즈가 줄어들음에 따라 사진의 반응형 조치에 대한 부분이 아직 자세히 안 나와서 큰 창기준으로만 했습니다.
- 백앤드가 작업 중이어서 이벤트 카드 하나만 임의로 만들어두고 컴포넌트 복붙해서 배치해두었습니다. 
---
> [DEV] 이벤트 페이지 이벤트 카드 배치

- src/app/api/main/getProjects/route.ts
- src/app/api/main/getTimelines/route.ts
- src/interfaces/NotionAPI.ts
- src/utils/NotionUtil.ts
메인페이지에 관한 API를 구성하였습니다.
- 메인페이지 관련 API를 구성하였습니다.
- `/api/main/getProjects` 경로로 접근 시, 메인에 표시할 프로젝트 데이터가 반환됩니다.
- `/api/main/getTimelines` 경로로 접근 시, 메인에 표시할 타임라인 데이터가 반환됩니다.
- 기존의 Member API 구현 과정에서 활용한 Util과 Interface를 활용하였으며, 유사하게 요청되는 부분을 함수로 분리하여 모듈화하였습니다.
- 현재, 알 수 없는 원인으로 Project Data 중 Image에 관련된 항목을 비활성화 해두었습니다. `console.log`로 확인하면 URL이 정상적으로 반환되나, Object로서 접근해 Project Data에 입력을 시도하면 undefined 이슈가 발생하고 있어, 추후 Member API에서 제외된 이미지 항목과 같이 개선 예정입니다.
> [DEV] BE 메인페이지 API

- src/utils/NotionUtil.ts
Image 정보를 반환하는 API에서 발생하는 더미이미지 문제를 수정하였습니다.
- 현재, 멤버와 메인 프로젝트/타임라인 API에서 이미지의 경우, 원인 불명의 Type 이슈로 인해 `IMAGE`와 같은 더미 문자열이 반환되도록 구현되어있습니다.
- 이로 인해, 일부 환경에서 올바르지 않은 Image URL로 인해 빌드 및 렌더링이 불가하던 문제를 수정하였습니다.
- `Pixabay`에서 제공하는 무료 CDN 이미지 링크로 대체하였습니다.
> [FIX] API Image 관련 더미값 수정

- package.json
- pnpm-lock.yaml
- src/app/api/blog/getList/[type]/route.ts
- src/app/api/event/getList/route.ts
- src/app/api/main/getProjects/route.ts
- src/app/api/main/getTimelines/route.ts
- src/app/api/member/getList/[year]/route.ts
- src/interfaces/Common.ts
- src/interfaces/FirebaseAPI.ts
- src/utils/FirebaseUtil.ts
- src/utils/NotionUtil.ts
프로젝트 Back-End에 Firebase Firestore API를 적용하였습니다.
- 메인 프로젝트 및 타임라인 API를 Firebase 기반으로 변경하였습니다.
- 멤버 리스트 API를 Firebase 기반으로 변경하였습니다.
- 블로그 및 이벤트의 리스트 API를 Firebase 기반으로 변경하였으며, 하위 객체 데이터에 `Notion ID` 값이 추가되었습니다.
- 기존 Notion API 코드는 일단 제거하지 않았습니다.
> [DEV] BE Firebase 적용

- src/app/_components/sections/projects/ProjectDesktopCard.tsx
- src/app/blog/[type]/[id]/page.tsx
- src/app/blog/[type]/layout.tsx
- src/app/blog/[type]/page.tsx
- src/components/common/PageHeader.tsx
블로그 디테일 페이지 제작
- 큰 틀은 제작 한것 같아요...!
부족한것
1. 페이지 헤더
1-1. 흰색선이 안나옴
1-2. 고정이 안됨
1-3. 글씨 눌렀을 때 목록 페이지로 링크 안됨
2. 이전 이후 포스트 버튼 Id 가 어떤식으로 올지 몰라서 링크 안걸려있음
> [DEV] blog detail

- next.config.js
- package.json
- pnpm-lock.yaml
- src/app/api/blog/getDetail/[type]/[id]/route.ts
- src/app/blog/[type]/[id]/_components/BlogNavigationButtons.tsx
- src/app/blog/[type]/[id]/_components/DevPostView.tsx
- src/app/blog/[type]/[id]/_components/NotionRenderer.tsx
- src/app/blog/[type]/[id]/_components/ProjectPostView.tsx
- src/app/blog/[type]/[id]/_components/index.ts
- src/app/blog/[type]/[id]/loading.tsx
- src/app/blog/[type]/[id]/page.tsx
- src/app/blog/[type]/layout.tsx
- src/app/blog/[type]/page.tsx
- src/app/blog/_components/BlogArticleView.tsx
- src/app/blog/_components/BlogHeader.tsx
- src/app/events/page.tsx
- src/components/common/Link.tsx
- src/components/common/PageHeader.tsx
- src/components/common/ThumbnailCard.tsx
- src/interfaces/Common.ts
- src/styles/nord.css
- src/utils/notion/BlogPost.ts
- src/utils/notion/NotionError.ts
- src/utils/notion/PageManager.ts
- src/utils/notion/index.ts
- tailwind.config.js
#87 이후 발생한 Merge Conflict를 Resolve합니다.
-  #87의 Merge 이후 발생한 Merge Conflict를 Resolve 합니다.
- 충돌하여 동작하지 않는 문제를 해결하였습니다만, Notion API가 올바르게 동작하지 않고 있습니다.
- 로컬에서 알 수 없는 Type Error로 발생하고 있어, 재확인이 필요할 것 같습니다.
- @danpacho Notion API 작업한거 Fix 부탁드립니다.
> [FIX] Resolve Merge Conflict

- src/app/members/[year]/layout.tsx
- src/app/members/_components/MemberCard.tsx
- src/app/members/_components/MemberHorizontalScrollView.tsx
- tailwind.config.js
멤버 데스크탑 페이지 수정사항 완료했습니다.
-버튼-헤더사이 간격
-호버됐을 때, 그라데이션 사이즈 조정
-YearButton 기수별로 나타내기
> [DEV] 멤버 데탑 페이지 수정사항 완료

- src/app/events/_components/EventCard.tsx
- src/app/events/page.tsx
Event 페이지 mobile UI 구현
Event 페이지 mobile UI 구현하였습니다.
페이지 축소할 때 씰룩씰룩 하는게 약간 거슬리는데 확인부탁드립니다!
> [DEV] Event 페이지 mobile UI 구현

- src/app/members/[year]/layout.tsx
- src/app/members/_components/MemberCard.tsx
- src/app/members/_components/MemberContact.tsx
- src/app/members/_components/MemberHorizontalScrollView.tsx
- src/app/members/_components/MemberRoleIcon.tsx
- tailwind.config.js
> [DEV] MemberPage_Mobile 구현 완료

- src/app/_components/sections/introduction/WhoAreWe.tsx
- src/app/members/[year]/layout.tsx
- src/app/members/[year]/page.tsx
- src/app/members/_components/MemberAvatar.tsx
- src/app/members/_components/MemberHorizontalScrollView.tsx
>MemberPage, MainPage fix
>MainPage Intro_Whoarewe 부분 padding 수정
>MemberPage Mobile UI Image 크기 조절
>데스크탑 비율에 따른 멤버 정렬
> [FIX] MemberPage, MainPage

- src/app/_components/sections/projects/ProjectDesktopCard.tsx
- src/app/_components/sections/projects/ProjectMobileCard.tsx
- src/app/_components/sections/projects/ProjectsSection.tsx
main페이지 project카드 글씨/사진 잘림을 해결하였습니다.
큰 모니터와 작은 해상도일때 잘 작동하는지 확인 부탁드려요!
>  [FIX] main페이지 project카드 글씨/사진 잘림 

- src/utils/notion/NotionRenderer.tsx
`react-notion-x` 라이브러리에서 제시 되는 collection 컴포넌트 에러를 해결했습니다.
> fix: react-notion-x collection component error

- src/app/members/[year]/layout.tsx
- src/app/members/_components/MemberHorizontalScrollView.tsx
>모바일 화면에서 center
>데탑 화면에서 페이지 크기에 따른 멤버 정렬 위치 조절
> [FIX] MemberPage fix

- src/app/_components/sections/timelines/TimelineCardView.tsx
timeline card 순서를 'yellow', 'purple', 'teal', 'yellow', 'hotpink'로 변경했습니다.
> [REFACTOR] timeline card color 순서

- src/app/_components/sections/projects/ProjectDesktopCard.tsx
- src/app/_components/sections/projects/ProjectsSection.tsx
- src/app/page.tsx
- mobile 환경에서 x-scroll이 생기는 것을 고쳤습니다.
- desktop component가 특정 사이즈에서 잘리는 문제를 고쳤습니다.
> [FIX] mobile `x-overflow` 문제 및 desktop 잘리는 현상

- src/app/events/layout.tsx
- src/app/events/page.tsx
- Event card가 정상적으로 위에 렌더링 되도록 수정했습니다.
- Event page의 백그라운드 svg가 절대 클릭되지 않도록 수정했습니다.
> [FIX] event card location 수정

- src/app/events/[id]/page.tsx
refactor: delete unnecessary code
issue제목에 해당하는 부분은 단팥초님이 수정하셨는데, 해당 페이지에 불필요한 코드가 있어서 수정했습니다. 이슈를 파기엔 사소해서 제 이슈도 닫을겸 이렇게 했습니다!
> [FIX] 이벤트 상세 글 join 버튼 수정

- src/utils/FirebaseUtil.ts
Event List 페이지의 정렬 기준을 변경하였습니다.
- Firebase Util 내부에서 기존에 별도의 정렬옵션 없이 오름차순 정렬하도록 구현되어있던 것을, `query` 함수와 `orderBy` 속성을 적용하여 Date 값을 기준으로 내림차순 정렬하도록 변경하였습니다.
- Firebase 관련 Key 환경변수가 `NEXT_PUBLIC` Prefix로 선언되어 Static Web 배포 시 유출 가능하던 것을 수정하였습니다.
> [FIX] Event List 정렬기준 변경

- src/app/_components/navBar/NavBarDesktop.tsx
- src/app/_components/navBar/NavBarMobile.tsx
Recruit 구글폼으로 이동하기 위한 버튼을 추가하였습니다.
- `NavBarDesktop` 및 `NavBarMobile` 컴포넌트 내에 Recruit Form으로 이동하기 위한 버튼을 추가하였습니다.
- 기존에 구성한 `NavButton`을 활용하였습니다.
> [DEV] Recruit 링크 추가

- src/app/_components/navBar/NavBarDesktop.tsx
- src/app/_components/navBar/NavBarMobile.tsx
Recruit 바로가기의 구현을 개선하였습니다.
- Mobile UI에서 Link 바로가기가 동작하지 않던 문제를 해결하였습니다. `RECRUIT_URL`의 환경변수를 `NEXT_PUBLIC` Prefix로 변경하였습니다.
- Desktop UI에서 애니메이션을 변경하였습니다. 기존의 텍스트 형식 Underline 애니메이션에서 Scale 애니메이션으로 변경하였습니다.
> [FIX] Recruit Link 개선

- src/app/_components/navBar/NavBarDesktop.tsx
- src/app/_components/navBar/NavBarMobile.tsx
recruting 버튼 제거했습니다.
- recruting 버튼 없앴습니다.
- 근데 다음 기수에 또 살릴수도 있을 것 같아서 주석처리 했어요
> [FIX] recruiting 버튼 제거
