src/app/layout.tsx
src/components/modal/index.ts
src/components/modal/modal.tsx
src/components/modal/useModal.ts

공용 modal component를 개발했습니다.
- `layout.tsx`의 `<div id="modal-root" />`에 modal을 렌더링합니다.
- modal 생성시 상단 nav-bar를 제외한 나머지 요소는 blur 처리 됩니다.
- Modal 컴포넌트와 useModal modal 상태관리용 훅을 함께 사용합니다.
1. Modal 컴포넌트: modal view입니다. `children`에 컴포넌트를 넣고 렌더링합니다.
2. useModal 훅: modal 상태관리 훅입니다. 반드시 Modal 컴포넌트에 open prop을 주입합니다.
1. 우선 `import { Modal, useModal } from '~/components/modal'`로 컴포넌트를 불러옵니다.
2. 다음과 같은 prop을 사용하여 modal의 움직임과 background blur level을 제어합니다.
```bash
blur="2xl"
onOutsideClick={action.close}
transitionDuration="duration-300"
modalOpenClassName="translate-x-0 scale-100"
modalCloseClassName="translate-x-1/2 scale-75"
```
3. 컴포넌트를 작성합니다.
```tsx
// use client notation 을 반드시 달아야 합니다.
'use client'
import { Modal, useModal } from '~/components/modal'
export const TestModal = () => {
// modal 상태관리용 …
```

[DEV] common modal 개발

---

src/app/_components/index.ts
src/app/_components/nav/index.tsx
src/app/layout.tsx
src/components/link/Link.tsx

scroll nav button을 추가했습니다.
- Next.js Link 컴포넌트로 projects, about us로 이동하는 버튼을 추가했습니다.
- `type="scroll"`을 추가하고 스크롤 타겟 요소의 `id`로 `href`속성을 적습니다.
```tsx
const Some = () => {
return  (
<NavButton type="scroll" href="/#about">
About us
</NavButton>
)
}
```
```tsx
const Page = () => {
return (
<div>
<h1 id="about">여기로 스크롤 됩니다.</h1>
<div/>
)
}
```

[DEV] add nav btn

---

src/app/api/blog/getDetail/[type]/[id]/route.ts
src/app/api/blog/getList/[type]/route.ts
src/app/api/event/getDetail/[id]/route.ts
src/app/api/event/getList/route.ts
src/app/api/main/getProjects/route.ts
src/app/api/main/getTimelines/route.ts
src/app/api/member/getList/[year]/route.ts

API 구현을 위한 라우팅을 구성하였습니다.
- 본격적인 API 개발 및 외부API 연동에 앞서, 본 프로젝트에서 필요로 하는 각 API에 대한 라우팅을 구성하였습니다.
- `/api/`를 경로의 Prefix로 하여 접근할 수 있습니다.
- Blog 관련 API는 `getList`와 `getDetail`로 구성되며, 각각 타입에 대한 전체 글 목록을 반환하는 함수와, 특정 글에 대한 상세 항목을 반환하는 함수입니다.
- Event 관련 API는 마찬가지로 `getList`와 `getDetail`로 구성되며, Blog API와 유사합니다.
- Member 관련 API는 전체 멤버 목록을 반환하는 `getList`로 구성되어 있습니다.
- Main에서는 타임라인 정보와 대표 프로젝트 목록을 반환하는 함수인 `getTimelines`와 `getProjects`로 구성됩니다.
- 각 함수는 현재 `HTTP GET`으로 정의되어있으며, 인자를 올바르게 입력한 경우에만 동작하도록 구성해두었습니다.

[DEV] API 라우팅 구성

---

src/components/link/Link.tsx

NavButton에서 발생하던 TypeError를 해결하였습니다.
- NavButton의 `/members` Link 항목에서 TypeError가 발생하던 것을 해결하였습니다.
- `Link.tsx` 내의 `LinkPath` Type 정의에서, `/members`가 아닌 `/members/${string}`으로 되어있던 것을 수정하였습니다.
- 추후 Blog 및 Event의 Link 구성을 위해, 하위 링크를 `/${string}`으로 갖는 두개 항목을 추가하였습니다.

[FIX] NavButton 링크 Type 이슈 해결

---

src/app/_components/benefits/BenefitModalSections.tsx
src/app/_components/benefits/index.tsx
src/app/_components/benefits/mentor/Mentor.tsx

Mainpage의 Benefit 파트 구현 완료했습니다.
- FadeIn 컴포넌트를 사용하여 인터렉션 구현 완료했습니다. 페이지를 내리면 해당 Title이 아래에서 위로 올라옵니다.
- Mainpage의 project 파트와 레이아웃 맞추기위해 benefit 틀 사이즈 수정했습니다.
`col-start` & `col-end`를 1-8에서 2-7로 수정했습니다.
- Universities 개수가 32 -> 36으로 변경되어 데이터 수정했습니다.
- 사진은 더미 데이터를 넣었습니다. 추후 사진을 받으면 사진을 교체할 예정입니다.

[DEV] Mainpage의 Benefit 파트 구현

---

src/app/api/blog/getDetail/[type]/[id]/route.ts
src/app/api/blog/getList/[type]/route.ts
src/app/api/event/getDetail/[id]/route.ts
src/app/api/event/getList/route.ts
src/app/api/main/getProjects/route.ts
src/app/api/main/getTimelines/route.ts
src/app/api/member/getList/[year]/route.ts
src/interfaces/common.ts
src/interfaces/index.ts
src/interfaces/routeParams.ts
tsconfig.path.json

API 동작에 Dummy 데이터 Response를 구성하였습니다.
- 이전에 #41 에서 정의한 Type Interface에 맞추어, 각 API의 Response 형식에 맞추어 Dummy 데이터를 구성하였습니다.
- Blog 및 Event의 경우, 각각 10개씩의 Dummy 데이터 항목을 List로 묶어 형식에 맞게 반환합니다.
- Member List의 경우, Dummy 멤버 데이터를 25명 반환하도록 하였습니다.
- Main Project 및 Main Timeline의 경우, 형식에 맞게 데이터를 구성하여 반환합니다.
- 각 API 함수에 대한 데이터 요청 방식은 다음과 같습니다. (모두 HTTP GET을 이용합니다)
Blog 및 Event의 Detail 함수 URL 맨 뒤 ID값은 자유롭게 입력해도 정상 작동합니다.
```
Design Blog Detail : `http://localhost:3000/api/blog/getDetail/Design/1`
Development Blog Detail : `http://localhost:3000/api/blog/getDetail/Development/1`
Project Blog Detail : `http://localhost:3000/api/blog/getDetail/Project/1`
Design Blog List : `http://localhost:3000/api/blog/getList/Design`
Development Blog List : `http://localhost:3000/api/blog/getList/Development`
Project …
```

[DEV] API Dummy 데이터 Response 구성

---

src/app/members/[year]/layout.tsx
src/app/members/[year]/page.tsx
src/app/members/_components/MemberHorizontalScrollView.tsx

PR에 대한 간단한 요약을 작성합니다.
member page desktop에서 overflow-x가 먹히지 않는 문제를 w-full로 해결했습니다.
변경된 사항은 다음과 같습니다.
1. `MemberHorizontalScrollView` 컴포넌트의 최상단 div를 제거하고 `w-full`을 추가합니다.
2. `MemberPage` 페이지 컴포넌트에 `w-full`를 추가합니다.
```ts
<div className="flex w-full flex-col py-4">
<MemberHorizontalScrollView members={members.RESULT_DATA.MEMBER_LIST} />
</div>
```
1. 너비 `1416px`
2. 너비 `981px`

[FIX] member layout

---

src/app/_components/sections/projects/ProjectDesktopCard.tsx
src/app/api/blog/getDetail/[type]/[id]/route.ts
src/utils/notion/BlogPost.ts

Main 페이지와 Blog List 페이지의 로직 이슈를 해결하였습니다.
- Main 페이지에서 Project Card의 onClick URL이 `/blog/Development`로 이동하던 것을 `/blog/Project`로 변경하였습니다. 추가로, Firebase DB상에서의 ID값을 수정해, 정상적으로 해당 포스팅 이동하도록 하였습니다.
- Blog Detail 페이지에서, 존재하지 않는 포스팅의 ID값으로 접근하는 경우, 기존의 Next Error가 아닌 `404` 페이지가 렌더링되도록 예외처리를 추가하였습니다.
- 기존 Issue #99 에서 언급한 Member List 관련 문제점의 경우, 정상적인 것으로 다시 확인되어 수정하지 않았습니다.

[FIX] Blog 및 Member 로직 이슈 해결

---

src/app/events/_components/TimeLineCard.tsx

timeline card가 특정 width에서 새로고침 시에 보이지 않는 에러를 해결했습니다.
`observerOption`을 조정했습니다.

[FIX] timeline card invisible error

---

src/app/events/_components/TimeLineCard.tsx

특정한 screen 사이즈에서 timeline card가 잘리는 문제를 해결합니다.

[FIX] timeline card width overflow issue

---

src/utils/fetcher.ts

API Fetch 시, Base URL을 조건에 따라 다르게 지정하도록 합니다.
- Vercel 및 Netlify의 배포시스템 상, 현재의 `localhost:3000` 주소로 요청이 불가하여 빌드가 진행되지 않는 이슈가 있습니다.
- Fetch Util을 수정하여 `NODE_ENV` 환경변수의 값과 `PUB_URL` 변수의 유무에 따라, 지정된 배포 URL 혹은 `localhost:3000`으로 Base URL이 구성되도록 하였습니다.
- Base URL은 `PUB_URL` 환경변수로 지정이 가능하며, `NODE_ENV`가 `production`이더라도 `PUB_URL`이 정의되지 않은 경우에는 `localhost:3000`으로 Fetch가 동작하도록 하였습니다.

[DEV] 배포시스템 대응 URL 분기처리

---

src/app/events/page.tsx
src/app/page.tsx

Pre-render 과정에서 Fetch가 불가하여 Static Build가 이루어지지 않는 문제를 해결하였습니다.
- Main 및 Event List Page에서 `export const dynamic = 'force-dynamic'` 구문으로 `Force-Dynamic Render`를 활성화하여 Static Build 과정에서 Pre-render를 Skip 하도록 하였습니다.

[FIX] Prerender 관련 Fetch Issue

---

src/app/blog/_components/BlogHeader.tsx
src/components/common/Footer.tsx

일부 텍스트에 존재하는 오타를 수정하였습니다.
- Blog List 페이지의 상단 Description 텍스트에 있는 띄어쓰기 오타를 수정하였습니다.
- Footer 개발자 이름 목록의 오타를 수정하였습니다. `Yongmin You` -> `Yongmin Yoo`

[FIX] Blog 페이지 및 Footer 텍스트 오타 수정

---

src/app/events/_components/TimeLineCard.tsx

timelinecard 2줄될 때 제목 사라지는 이슈 수정했습니다

[FIX] timelinecard margin

---

src/interfaces/Common.ts
src/utils/notion/BlogPost.ts

- Post를 createAt을 기준으로 내림차순 정렬로 변경하였습니다.
- `BLOG_CREATED_AT: string`을 `BLOG_POST_META`에 추가했습니다.
- 기존 updatedAt은 각 post 페이지의 날짜에 표시됩니다.

[FIX] post createdAt 기반 내림차순 정렬

---

next.config.js
src/app/members/_components/MemberCard.tsx

멤버 카드에 이미지가 깨지는 에러를 해결했습니다.
- 멤버 이미지가 사진과 같이 로컬 환경에서는 401에러가, 배포 환경에서는 502에러가 나타나는 문제를 해결했습니다.
- 멤버 사진을 노션에서 관리하는데, Firebase에 저장할때 이미지 링크를 다음과 같이 변경했습니다.
노션에서 접근한 주소 `www.notion.so`  ->  웹에 게시된 노션에서 접근한 주소 `gdsc-cau.notion.site`
- Firebase에 1기~3기의 이미지 링크를 수정했고, 4기 멤버(58명)의 정보도 업데이트 해두었습니다.
- 로컬에서는 이미지가 잘 뜨긴 하지만, 배포환경에서도 멤버 이미지가 잘 뜨는 것을 확인한 후에 나머지 깨지는 사진(대표 프로젝트 사진, 이벤트 사진)들도 수정하겠습니다.
- 머지가 되면 꼭 멤버 사진이 잘 뜨는지 확인해주시면 감사하겠습니다!!
[궁금한 점]
- 멤버 카드 뒷면에 contacts를 map(email, github, instagram)으로 불러오는 로직이 있습니다. 기존에는 이 contacts를 key값으로 두었는데, 이번 기수에는 이 세가지를 모두 빈칸으로 둔 사람들이 많아서 에러가 발생했었습니다. 그래서 값이 없는 경우에는 index로 값을 따로 두었는데, 혹시 이 방법 말고 더 좋은 방법이 있을지 궁금합니다!

[FIX] 멤버 이미지 연동 에러 

---

src/app/members/_components/MemberCard.tsx
src/app/members/_components/MemberContact.tsx

멤버 카드 뒷면 contact 관련하여 수정사항이 있었습니다.
- 개발자의 github처럼 디자이너분들에게는 behance라는 주소항목이 있습니다. 그런데 현재 멤버 카드 뒷면에 behance항목이 누락되어서 추가했습니다.
- contacts의 4가지 항목이 모두 비어있을 경우에 아무것도 렌더링 하지 않게 되어있는데, 항목이 모두 비어있는 경우에도 email 아이콘이 나타나서 조건을 추가했습니다. 
-> firebase를 확인해봤을때도 빈칸이 없었는데 왜 이메일 아이콘만 나타나는지 모르겠습니다..?

[FIX] 멤버 카드 뒷면 contact 관련

---

src/app/_components/navBar/NavBarDesktop.tsx
src/app/members/page.tsx
src/components/common/Link.tsx

- Members 페이지에서 3기로 이동하던 네비게이션을 4기로 변경했습니다.
- 원래는 LATEST_YEAR 값을 4로 업데이트하면 자동으로 반영될 줄 알았지만, 네비게이션 바(`NavBarDesktop.tsx`)에 하드코딩되어 있어서 직접 수정해야 했습니다.
- 다음 리팩토링 시 참고하실 수 있도록 기록해둡니다!
---

[FIX] Members 페이지 네비게이션 변경

---

src/app/blog/_components/BlogArticleView.tsx

블로그 Development 탭의 아티클 목록을 시간 순으로 정렬 처리했습니다. #154 
- 노션에서 어떤 식으로 처리되는 것인지 모르겠으나 BLOG_CREATED_AT보다 BLOG_UPDATED_AT이 작성자가 아티클을 등록한 날짜에 더 가깝다고 판단하여 정렬 기준으로 선정했습니다.
- 아티클 카드에 사용하는 날짜가 BLOG_UPDATED_AT인 것을 확인했습니다. (`/blog/_components/card/DevelopCard.tsx`)
---
전후 비교
- 정렬 전
- 정렬 후

[FIX] 블로그 아티클 시간 순 정렬

---

src/app/blog/_components/BlogArticleView.tsx
tailwind.config.js

화면폭이 변경될 때 Project 카드가 겹쳐지는 문제를 해결했습니다.
- 화면 폭을 조정할 때 위와 같이 프로젝트 카드가 겹치는 문제가 발생했습니다.
- 기존 코드는 반응형이지만 페이지의 좌우 패딩이 고려되지 않아 특정 폭 구간에서 오버플로우가 발생하였습니다.
- 반응형 그리드뷰로 수정하였습니다.
- tailwind의 breakpoint를 사용해 오버플로우가 발생하는 폭의 값을 기준으로 그리드가 조정되도록 하였습니다.
- 모바일뷰는 1열, 데스크탑뷰는 3열, 그 사이는 2열로 구성됩니다.

[FIX] Project 카드 겹침 해결
